# Generated by Django 4.0.1 on 2022-06-04 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsstory_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='story_img',
            field=models.ImageField(blank=True, null=True, upload_to='she_codes_news/news/static/news/images/'),
        ),
    ]
