# Generated by Django 4.0.1 on 2022-12-09 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_newsstory_category_alter_newsstory_story_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsstory',
            old_name='story_img',
            new_name='image',
        ),
    ]
