# Generated by Django 4.0.1 on 2022-06-04 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsstory_story_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='story_img',
            field=models.CharField(default='upload', max_length=500),
        ),
    ]
